export const FIND_TEAMS = "FIND_TEAMS";
export const SELECTED_TEAM = "SELECTED_TEAM";
export const FONT_CHANGED = "FONT_CHANGED";
export const IMAGE_ROTATED = "IMAGE_ROTATED";
export const FIND_NCAA_TEAMS = "FIND_NCAA_TEAMS";
