export const FIND_TEAMS = "FIND_TEAMS";
export const SELECTED_TEAM = "SELECTED_TEAM";
export const FONT_CHANGED = "FONT_CHANGED";
export const JERSEY_TEXT_CHANGED = "JERSEY_TEXT_CHANGED";
export const JERSEY_TEXTCOLOR_CHANGED = "JERSEY_COLOR_CHANGED";

export const RETAILER_IMAGE_STATS = "RETAILER_IMAGE_STATS";
export const RETAILER_IMAGES = "RETAILER_IMAGES";

export const ASSIGN_IMAGES_TO_TEAM = "ASSIGN_IMAGES_TO_TEAM";
