export const FIND_TEAMS = 'FIND_TEAMS'
export const SELECTED_TEAM = 'SELECTED_TEAM'
export const FONT_CHANGED = 'FONT_CHANGED'
export const JERSEY_TEXT_CHANGED = 'JERSEY_TEXT_CHANGED'
export const JERSEY_TEXTCOLOR_CHANGED = 'JERSEY_TEXTCOLOR_CHANGED'
export const BASE_COLOR_CHANGED = 'BASE_COLOR_CHANGED'
export const JERSEY_TEAMCREST_CHANGED = 'JERSEY_TEAMCREST_CHANGED'
export const JERSEY_TEXT_STYLE_CHANGED = 'JERSEY_TEXT_STYLE_CHANGED'
export const JERSEY_TEXT_SIZE_CHANGED = 'JERSEY_TEXT_SIZE_CHANGED'
export const JERSEY_SLEEVE_UPDATED = 'JERSEY_SLEEVE_UPDATED'
export const PANT_SIDE_UPDATED = 'PANT_SIDE_UPDATED'
export const JERSEY_GRAPHIC_UPDATED = 'JERSEY_GRAPHIC_UPDATED'
export const ATTRIBUTE_COLOR_UPDATED = 'ATTRIBUTE_COLOR_UPDATED'

export const RETAILER_IMAGE_STATS = 'RETAILER_IMAGE_STATS'
export const RETAILER_IMAGES = 'RETAILER_IMAGES'

export const ASSIGN_IMAGES_TO_TEAM = 'ASSIGN_IMAGES_TO_TEAM'

export const TEAM_IMAGE_STATS = 'TEAM_IMAGE_STATS'
export const TEAM_IMAGES = 'TEAM_IMAGES'

export const FETCH_USER = 'FETCH_USER'

export const FIND_ORDERS = 'FIND_ORDERS'

export const ORDER_STATS = 'ORDER_STATS'

export const CREATE_TEAM = 'CREATE_TEAM'
export const GET_TEAMS = 'GET_TEAMS'
